<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="IM-RT-LP-074" name="com.web.tests.TIDTESTCASES.TIDTestCasesTest" tests="2" failures="1" timestamp="29 Nov 2016 10:52:12 GMT" time="175.967" errors="0">
  <testcase name="InvalidWebAutomationTest" time="40.019" classname="com.web.tests.TIDTESTCASES.TIDTestCasesTest">
    <failure type="java.lang.AssertionError" message="Application Login Failed, Test Failed">
      <![CDATA[java.lang.AssertionError: Application Login Failed, Test Failed
	at org.testng.Assert.fail(Assert.java:94)
	at com.web.modules.LOGIN.LoginPage.clickLoginBtn(LoginPage.java:113)
	at com.web.modules.LOGIN.LoginPage.portalSignIn(LoginPage.java:75)
	at com.web.tests.TIDTESTCASES.TIDTestCasesTest.InvalidWebAutomationTest(TIDTestCasesTest.java:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- InvalidWebAutomationTest -->
  <testcase name="ValidWebAutomationTest" time="135.948" classname="com.web.tests.TIDTESTCASES.TIDTestCasesTest"/>
</testsuite> <!-- com.web.tests.TIDTESTCASES.TIDTestCasesTest -->
